### ISSUE TITLE
Handlebars

### ISSUE THREAD

**Issue by stevenvachon** [daffl/breezy#5]
My template preference is full-on Handlebars, very much like what you Bitovi guys have going with [CanJS](https://github.com/bitovi/canjs).

If you feel the same, you might be interested in two projects that I'm currently working on: [handlebars-virtual-dom](https://github.com/stevenvachon/handlebars-virtual-dom) (haven't started yet) and its main dependency, [handlebars-html-parser](https://github.com/stevenvachon/handlebars-html-parser) (coming along nicely) which makes compiling super easy. I have plans to write similar compilers for other virtual DOMs like React and Mithril as well as a universal runtime that works for all of them, providing various helper functions and such.

I had originally planned on creating a new framework, but it'd be so similar to what you have here with breezy that perhaps it'd be best for us to collaborate.

**Comment by daffl** [comment]
The whole point of this was to create a syntax that is more HTML5-friendly (which I think attributes much of the current success of Angular) because web applications are well... built in HTML5. So far I did not come across a use case where this syntax is inferior to Handlebars. Just looking at how many times I have done something like:

```html
<ul>
{{#each todos}}
  <li class="{{#if active}}active{{/if}}{{#if isSelected}}selected{{else}}muted{{/if}}">{{description}}</li>
{{/each}}
</ul>
```

I find this - besides being valid HTML5 - a lot more concise:

```html
<ul>
  <li for-each="todos" class="{{active ? 'active'}} {{isSelected ? 'selected' : 'muted'}}">{{description}}</li>
</ul>
```

It might be also worth comparing the [CanJS](https://github.com/tastejs/todomvc/blob/gh-pages/examples/canjs/index.html#L17) and [Breezy](https://github.com/daffl/breezy/blob/master/examples/public/index.html) TodoMVC templates.

I briefly considered making a Handlebars virtual-DOM implementation but my personal conclusion is that - in the long term - Handlebars is not an appropriate templating language for HTML templates.

**Comment by stevenvachon** [comment]
Fair enough.

I'd attributed Angular's success to how it uses standard JavaScript objects (via dirty checking). If I were to pick something inappropriate in Angular's template syntax, it would be its non-HTML5 spec use of HTML5; `ng-repeat` as well as `for-each` are not a part of it. A virtual DOM removes the need for such attributes anyway.

The thing I really like about Handlebars is that it never attempts to manipulate the HTML spec. Instead it just wraps it.

**Comment by daffl** [comment]
I'm pretty sure custom attributes (just like custom tags) are part of the HTML5 spec (I could be totally wrong though). The appealing thing is that you just need to know HTML instead of learning an entirely new syntax. I guess Expressions are its own syntax, too but it's very close to JavaScript. Angular mistreated that a lot by basically having its entirely own syntax in attributes again.

I'm curious how the VDOM would remove the need for custom attributes though?

**Comment by stevenvachon** [comment]
Angular has "directives" because its reactive binding is done so with and on the DOM without a traditional string-parsed template system. With a template string compiled to a virtual DOM render function, that logic can come from anything, which de-necessitates the use of custom attributes. The _choice_ to opt for such is, of course, another story.

Custom attributes without a prefixed `data-` can exist on custom elements, but not on standard ones.

As for learning a new syntax, to me, such custom attributes cause confusion by blurring the lines between HTML and template logic.

_(edited for better accuracy)_

**Comment by stevenvachon** [comment]
As for learning a new syntax, to me it causes confusion by blurring the lines between HTML and template logic.

**Comment by stevenvachon** [comment]
^ I've updated the wording on my above comment for better accuracy.

**Comment by daffl** [comment]
`data-` attributes can definitely exist everywhere (that is part of the HTML5 spec). You might be right about custom attributes on standard attributes. The question is, why would you need a custom templating DSL (like Handlebars) if it can all be done through valid HTML.

@matthewp wrote up many good points for HTML based templates at http://matthewphillips.info/posts/im-sold-on-html-based-templating.html. The main point is the advent of web components. To quote from the post:

> Then Web Components came around (which I've written about here) and introduced the <template> tag. The template tag brought some major benefits; namely that the content is parsed but not executed.

Non valid HTML templating languages will always need to be parsed somewhere and keep having an overhead that web components might be able to eliminate.

**Comment by stevenvachon** [comment]
I think the biggest thing is that DSLs like Mustache/Handlebars are logic-less (or mild pseudo-logic). Not only can non-engineers work with them more easily, they separate concerns. The difference between markup and "logic" is very stark yet simple.

Expressions are cryptic; especially ternary operations. Conversely, I think anyone who understands HTML can understand `{{#if var}}<tag/>{{/if}}` or `<tag {{#if var}}attr=""{{/if}}/>`.

With both we're still going to have `{{var}}`, and that is a form of DSL.
